<?php /* Smarty version 2.6.20, created on 2016-02-09 15:12:42
         compiled from video-new.tpl */

$this->_cache_serials['/home/admin/domains/hipmat.com/public_html/Smarty/templates_c/%%26^269^269879B4%%video-new.tpl.inc'] = '6ca88dd644b8874f1261724e7a2ef1f4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_advanced_video_list', 'video-new.tpl', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_6ca88dd644b8874f1261724e7a2ef1f4_0(&$_smarty)
{
echo smarty_get_advanced_video_list(array('assignto' => 'advanced_video_list','tag' => 'Hot','limit' => 5), $_smarty);
}



?>
