<?php /* Smarty version 2.6.20, created on 2016-07-18 00:41:16
         compiled from header.tpl */

$this->_cache_serials['/home/hipmatco/public_html/Smarty/templates_c/%%F7^F7F^F7F34188%%header.tpl.inc'] = '9c60f457e36b618db43fb7ac227eca80';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'header.tpl', 170, false),array('function', 'dropdown_menu_video_categories', 'header.tpl', 287, false),array('function', 'dropdown_menu_article_categories', 'header.tpl', 295, false),)), $this); ?>
<?php
function _smarty_tplfunc_9c60f457e36b618db43fb7ac227eca80_0(&$_smarty)
{
echo smarty_art_html_list_categories(array('max_levels' => 3), $_smarty);
}



?>
